name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    # - uses: amondnet/vercel-action@v20 #deploy
    #     with:
    #       vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
    #       github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
    #       vercel-args: '--prod' #Optional
    #       vercel-org-id: ${{ secrets.ORG_ID}}  #Required
    #       vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
    #       working-directory: ./sub-directory
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.7.8
      with:
        args: deploy --dir=build --prod
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'nextjs-github-actions-heroku'
        heroku_email: '<enter_your_email>@gmail.com'

